# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a359c4689669eef4c25f361f1e6a17a55c0e3711ec69df7326a686263e519c386d990d9057a393e459d1927e6d4b6f257048377bcdb8d4eb63dbf0c8647f8ecb

test:
  secret_key_base: 4a98af73503c9f5306fafe0b6ee6d84e5943be815fdce2bee0b746d7f87be6cf4773ffa446adc2df436a816a39279cbc1618b97a27df66cf0937b1e3a622782e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
